services:
  surrealdb:
    image: surrealdb/surrealdb:${SURREALDB_VERSION}
    restart: unless-stopped
    command: start -u ${SURREALDB_USER} -p ${SURREALDB_PASSWORD} -l ${SURREALDB_LOG_LEVEL} -- file://surrealdb-data
    volumes:
      - type: volume
        source: surrealdb-data
        target: /surrealdb-data
        volume:
          nocopy: true
    networks:
      - surreal-db

volumes:
  surrealdb-data:

networks:
  default:
    name: db
    external: true

  surreal-db:
    external: true

  postgresql-db:
    external: true
