services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
      args:
        NGINX_CONF: ${NGINX_CONF}
        NGINX_HTML: ${NGINX_HTML}
        NGINX_TEMPLATES: ${NGINX_TEMPLATES}
    restart: unless-stopped
    ports:
      - ${NGINX_HTTPS_PORT}:443
    volumes:
      - ${SSL_CERT_DIR}:/certs:ro
    environment:
      SITE_SERVER_NAME: ${SITE_SERVER_NAME}
      
  # keycloak:
  #   image: quay.io/keycloak/keycloak:20.0.0
  #   restart: unless-stopped
  #   volumes:
  #     - ${SSL_CERT_DIR}:/certs:ro
  #   environment:
  #     AUTH_SERVER_NAME: ${AUTH_SERVER_NAME}

networks:
  default:
    name: web
    external: true
